POST http://localhost:3001/posts HTTP/1.1
Content-Type: application/json

{
  "title": "top post ever 66",
  "content": "test post 66",
  "imageUrl": "https://fastly.picsum.photos/id/984/280/150.jpg?hmac=euassnkw4L-LpUwbpybmjW07RMpQ8R4m38dRTtnIkrw"
}


